# Generated by Django 2.0.2 on 2018-03-30 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('sexo', models.BooleanField(default=True)),
                ('vih', models.BooleanField(default=True)),
                ('diabetes', models.BooleanField(default=True)),
                ('hab_calle', models.BooleanField(default=True)),
                ('info_clinica', models.BooleanField(default=True)),
                ('observaciones', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
