# Generated by Django 2.0.1 on 2018-04-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diabetes',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hab_calle',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='info_clinica',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexo',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vih',
            field=models.NullBooleanField(default=True),
        ),
    ]
